routes:

  # list of routes

  home:
    default: true
    url: /
    templateUrl: home/home.html
    controller: HomeController

  error:
    url: /error
    templateUrl: error/error.html

    ./:
      err404:
        default: true
        url: /404
        templateUrl: error/error-404.html
        controller: HomeController